### ISSUE TITLE
Problem with Devise encryption module due to deprecated syntax.

### ISSUE THREAD

**Issue by ziyadbasheer** [jni-/Rails3-devise-ajax-login#1]
[DEVISE] Devise.use_salt_as_remember_token is deprecated and has no effect. Please remove it.

http://stackoverflow.com/questions/10610919/devise-new-errors-encrytable

If you're using encryptable on your models, you will now have to include devise-encryptable on your gemfile.

**Comment by jni-** [comment]
There is also issues with devise updating to 2.1 since this project is quite old and was pretty much left to itself - i'll fix these in another issue. Thanks for the feedback!

**Comment by ziyadbasheer** [comment]
My pleasure!
